新服务列表
FloatTech/zbputils pull request #12
Opened 2022-11-08 16:07 UTC by Jiang-Red

2022-11-09 05:27 UTC, fumiama requested changes
改好后，绘图逻辑请新建仓库，在此处仅用依赖。

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +	bannerpath = "zbpbanner/"
统一放data下

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +	PluginName   string
小写并省略无用前缀`Plugin`，如`name`

2022-11-09 05:27 UTC, fumiama commented on control/rule.go
> +				err = renderusage(ctx, service, gid)
不应在渲染函数完成发送逻辑，要降低耦合度。

2022-11-09 05:27 UTC, fumiama commented on control/rule.go
> +				err = renderimg(ctx)
耦合

2022-11-09 05:27 UTC, fumiama commented on control/rule.go
> +				_, err = file.GetLazyData(kanbanPath+"icon.jpg", true)
`GetLazyData`将直接返回`data`，可以考虑使用之，而非之后再读取一遍。

2022-11-09 05:27 UTC, fumiama commented on control/rule.go
> +				_, err = file.GetLazyData(kanbanPath+"icon.jpg", true)
同

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +	_ = os.MkdirAll(bannerpath, 0755)
panic

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +	_ = os.MkdirAll(bannerpath+"network/", 0755)
不应区分本地和network

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +func renderimg(ctx *zero.Ctx) (err error) {
- 应起一个更易理解的名字，如`func drawservicesof(gid int64) (imgs [][]bytes, err error)`
- 不应直接传递ctx。ctx唯一用到的地方只有gid，至于fake forward node，请移动至调用处。

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +	var plist = make([]*plugininfo, 0, len(priomap))
```go
plist := make([]*plugininfo, len(priomap))
```

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +		plist = append(plist, &plugininfo{
```go
plist[i] = &plugininfo{
	PluginName:   manager.Service,
	PluginBrief:  manager.Options.Brief,
	PluginBanner: manager.Options.Banner,
	PluginStatus: manager.IsEnabledIn(gid),
}
```

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +	var k int
k := 0

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +	page := len(plist) / 27
27应作为const定义在顶部，如`PAGECNT = 27`

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +		page--
- 确定不会出现`-1`？
- 正常逻辑应该是
```go 
page := len(plist)/27
if len(plist)%27 != 0 {
    page++
}
```

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +		imgw := 1272.0
同理，应定义一个const

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +		canvas := gg.NewContext(int(imgw), 30+30+300+(9*(256+30)))
硬编码坏，都应定义const，以下皆同，不再指出。

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +		canvas.DrawString("服务列表", 25, 30+40+55+canvas.FontHeight()-canvas.FontHeight()/3)
说好的封装呢，这样不就只能用来画服务列表了吗。这些可变的都应作为参数传递。以下皆同。

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +func drawplugin(canvas *gg.Context, x, y float64, i int, list *plugininfo) (err error) {
drawcard，毕竟不一定是画plugin

2022-11-09 05:27 UTC, fumiama commented on control/servicepic.go
> +func renderusage(ctx *zero.Ctx, s *ctrl.Control[*zero.Ctx], gid int64) (err error) {
rendertitledtext

2022-11-13 21:33 UTC, Jiang-Red commented
~~没测过~~

2022-11-15 02:43 UTC, fumiama approved these changes

2022-11-15 02:43 UTC, merged