add: 此处启用/禁用所有插件
FloatTech/zbputils pull request #19
Opened 2023-01-17 12:24 UTC by Jiang-Red

2023-01-17 15:11 UTC, fumiama requested changes
壞了，lint怎麼又開始了，江琳琳看看怎麼不要改讓他這些

2023-01-17 16:32 UTC, Jiang-Red commented
> 壞了，lint怎麼又開始了，江琳琳看看怎麼不要改讓他這些

查了一下看起来是nolint语法不对，然后就改了改，顺便删了没有用的lint check

2023-01-19 09:09 UTC, fumiama requested changes
删除的是因为什么呢？是暂时不支持泛型吗，是的话其实不用删，等他支持了自动就能用。如果确有必要原因，你可以将其注释而非删除。

2023-01-19 09:19 UTC, Jiang-Red commented
rowserrcheck是因为泛型，另外三个都是被弃用的

2023-01-19 09:29 UTC, fumiama approved these changes
ok

2023-01-19 09:29 UTC, merged