Feature gui 20230128
FloatTech/zbputils pull request #24
Opened 2023-02-23 13:39 UTC by guohuiyuan

2023-02-25 05:32 UTC, fumiama requested changes
- 尽量将繁琐的工作转移到前端
- 尽量让代码精简
- 警惕sql注入
- 不要让webui影响到现有行为

2023-02-25 05:32 UTC, fumiama commented on control/rule.go
> +		zero.OnRegex(`^/设置webui配置\s(.*[^\s$])\s(.+)$`, zero.SuperUserPermission).SetBlock(true).
配置这个提示太宽泛了，应具体到设置什么。

2023-02-25 05:32 UTC, fumiama commented on control/rule.go
> +				ctx.SendChain(message.Text("成功设置webui配置\nusername: ", regexMatched[1], "\npassword: ", regexMatched[2]))
你还输出一遍密码，这不太安全。发送者发送之后我建议也撤回。

2023-02-25 05:32 UTC, fumiama commented on control/web/common/response.go
> +	validate *validator.Validate
var validate = validator.New()

2023-02-25 05:32 UTC, fumiama commented on control/web/common/response.go
> +func Result(code int, result any, message string, messageType string, ctx *gin.Context) {
有必要封装这一层吗？反而会让代码更加晦涩。

2023-02-25 05:32 UTC, fumiama commented on control/web/common/response.go
> +func Ok(ctx *gin.Context) {
我的建议是
```go
type guictx gin.Context
func (ctx *guictx) Ok() { ... }
func (ctx *guictx) OkWithMessage() { ... }
```

2023-02-25 05:32 UTC, fumiama commented on control/web/controller/manage.go
> +	uuid "github.com/satori/go.uuid"
用google的那个uuid

2023-02-25 05:32 UTC, fumiama commented on control/web/controller/manage.go
> +	requestData sync.Map
使用RomiChan/syncx

2023-02-25 05:32 UTC, fumiama commented on control/web/controller/manage.go
> +	upGrader    = websocket.Upgrader{
upgrader是一个词，无需驼峰。

2023-02-25 05:32 UTC, fumiama commented on control/web/controller/manage.go
> +	log.SetOutput(writer)
这会导致目前log输出格式变化。我建议你观察一下log在windows、linux下的变化，尽量让它保持不变，至少颜色不能丢。

2023-02-25 05:32 UTC, fumiama commented on control/web/controller/manage.go
> +	connHandle := func(ctx *zero.Ctx) {
把这个直接写到Handle()里更直观。

2023-02-25 05:32 UTC, fumiama commented on control/web/controller/manage.go
> +			mi := types.MessageInfo{
这是一层协议转换，能否直接用ctx.Event？

2023-02-25 05:32 UTC, fumiama commented on control/web/controller/manage.go
> +		r := &request{
同样的，是一个协议转换。我建议能用ctx.Event代替就不要新建结构了，尽量保持代码精简。至于typename的翻译，完全可以在前端实现。

2023-02-25 05:32 UTC, fumiama commented on control/web/gui.go
> +func InitGui(addr string) {
包这一层没啥意思，不如让调用者自己go。

2023-02-25 05:32 UTC, fumiama commented on control/web/utils/cache.go
> +// Package utils 工具类
这个包意义不明，建议合并到其它地方。

2023-02-25 05:32 UTC, fumiama commented on control/webui.go
> +		process.GlobalInitMutex.Lock()
你忘了Lock和Unlock要成对出现吗

2023-02-25 05:32 UTC, fumiama commented on control/webui.go
> +	udbFolder = "data/webui/"
webui folder

2023-02-25 09:17 UTC, guohuiyuan commented
> * 尽量将繁琐的工作转移到前端
> * 尽量让代码精简
> * 警惕sql注入
> * 不要让webui影响到现有行为

数据的计算在后端，后端返回的数据尽量满足前端需求

2023-02-25 09:35 UTC, fumiama commented
前端不好改吗？

2023-02-25 09:37 UTC, guohuiyuan commented
> 前端不好改吗？

不要让前端请求多个接口拿数据，一次拿到数据

2023-02-25 09:39 UTC, fumiama commented
我又没说让他请求多个接口，我只是说后端不要做一些没用的事情，比如把typename换成中文啥的。

2023-02-25 09:41 UTC, guohuiyuan commented
> 我又没说让他请求多个接口，我只是说后端不要做一些没用的事情，比如把typename换成中文啥的。

这个改了

2023-02-25 09:43 UTC, fumiama commented
我知道你改了，我的意思就是，如果有其它类似问题，请一并处理。

2023-02-25 14:42 UTC, guohuiyuan commented
基本上改完了

2023-02-26 05:30 UTC, fumiama requested changes

2023-02-26 05:30 UTC, fumiama commented on control/rule.go
> +		zero.OnRegex(`^/设置webui账号\s(.*[^\s$])\s(.+)$`, zero.SuperUserPermission).SetBlock(true).
/设置webui账号用户名 xxx 密码 xxx

2023-02-26 05:30 UTC, fumiama commented on control/rule.go
> +				err := CreateOrUpdateUser(User{Username: regexMatched[1], Password: regexMatched[2]})
用&User参数。

2023-02-26 05:30 UTC, fumiama commented on control/rule.go
> +		zero.OnFullMatchGroup([]string{"/启动webui", "/停止webui"}, zero.SuperUserPermission).SetBlock(true).
OnCommandGroup
/webui
然后检测arg是启动还是停止
如：/webui启动 /webui停止

2023-02-26 05:30 UTC, fumiama commented on control/rule.go
> +	SignChan = make(chan bool)
应当用更加清晰的名字，如`ListenCtrlChan`

2023-02-26 05:30 UTC, fumiama commented on control/rule.go
> +				if matched == "/启动webui" {
所以这里就可以是
```go
xxxchan <- arg == "启动"
ctx.SendChain(message.Text(arg + "成功"))
```

2023-02-26 05:30 UTC, fumiama commented on control/web/common/response.go
> +func OkWithData(result any, ctx *gin.Context) {
这些封装太晦涩了，也完全没必要，不要这么写。

2023-02-26 05:30 UTC, fumiama commented on control/web/controller/manage.go
> +	conn = con
我不建议用这种晦涩写法。所有函数的效果应当在外部就可见。比如这里，你可以将conn返回，在外部再做处理。其它地方同理。

2023-02-26 05:30 UTC, fumiama commented on control/web/controller/manage.go
> +	if logConn != nil {
logConn完全没必要作为全局变量，它可以写入logWriter内部。真正需要做全局变量的是logWriter。始终记得尽量减少全局变量的使用，这是防止程序错误的重要一环，其它地方同理。

2023-02-26 14:26 UTC, guohuiyuan commented
改不动, 像那个conn是抄以前写的

2023-02-27 03:51 UTC, fumiama requested changes

2023-02-27 03:51 UTC, fumiama commented on go.mod
> +	github.com/guohuiyuan/ZeroBot-Plugin-Webui v0.0.0-20230226142052-988dacca5f95
移到floattech，我给你 https://github.com/FloatTech/bot-manager 的权限，你直接改那个库。把你的代码直接覆盖过去，但是包名改一下。

2023-02-27 03:51 UTC, fumiama commented on control/web/gui.go
> +			server = &http.Server{
有必要在这里再写一遍吗？

2023-02-27 03:51 UTC, fumiama commented on control/web/gui.go
> +	for flag := range control.ListenCtrlChan {
起名字清晰点，如`canrun`

2023-02-27 03:51 UTC, fumiama commented on control/web/gui.go
> +			if err := server.Shutdown(context.TODO()); err != nil {
不必提前shutdown。

2023-02-27 03:51 UTC, fumiama commented on control/web/controller/manage.go
> +func (l logWriter) Write(p []byte) (n int, err error) {
在shutdown状态下就不应该记录了，此时应当令l.logConn=nil

2023-02-28 10:00 UTC, fumiama commented on go.mod
> +	github.com/guohuiyuan/ZeroBot-Plugin-Webui v0.0.0-20230226142052-988dacca5f95
额，你听不明白我的意思吗，我让你直接覆盖文件到 https://github.com/FloatTech/bot-manager ，没让你移动仓库进来，bot-manager已经不再使用了，现在刚好让它恢复。而你移动新的仓库，就显得冗余了（而且你不觉得你包名画风不对吗😂）

2023-03-07 16:20 UTC, fumiama approved these changes

2023-03-07 16:21 UTC, merged

2023-03-07 16:21 UTC, fumiama commented
更新一下主仓库的PR，过一下lint即可。