修改brief提示信息；修改部分指令权限；使用txt保存服务列表显示行数信息
FloatTech/zbputils pull request #31
Opened 2023-04-08 15:50 UTC by fangliuyu

2023-04-08 16:26 UTC, fumiama requested changes

2023-04-08 16:26 UTC, fumiama commented on control/rule.go
> +			mun, _ := strconv.Atoi(binary.BytesToString(data))
check err

2023-04-08 16:33 UTC, fangliuyu commented on control/rule.go
> +			mun, _ := strconv.Atoi(binary.BytesToString(data))
respect

2023-04-08 16:47 UTC, fumiama requested changes

2023-04-08 16:47 UTC, fumiama commented on control/rule.go
> +				panic(err)
不要panic，warn一下即可。

2023-04-09 03:07 UTC, fumiama requested changes

2023-04-09 03:07 UTC, fumiama commented on control/rule.go
> +				logrus.Warning("获取设置的服务列表显示行数错误,将使用默认的显示行数\n", err)
```go
logrus.Warnln("[control] 获取设置的服务列表显示行数错误, 将使用默认的显示行数:", err)
```

2023-04-09 03:07 UTC, fumiama commented on control/rule.go
> +				logrus.Infoln("获取到当前设置的服务列表显示行数为: ", lnperpg)
```go
logrus.Infoln("[control] 获取到当前设置的服务列表显示行数为:", lnperpg)
```

2023-04-09 03:07 UTC, fumiama commented on control/rule.go
> +				panic(err)
说了不要panic，怎么漏了这里

2023-04-09 03:32 UTC, fumiama commented
复制粘贴不会吗，我帮你改吧。

2023-04-09 03:33 UTC, fumiama approved these changes

2023-04-09 03:33 UTC, merged