添加job管理界面
FloatTech/zbputils pull request #32
Opened 2023-04-09 12:04 UTC by guohuiyuan

2023-04-09 14:23 UTC, fumiama requested changes
不允许给job增加web，这相当于引用了web，导致web无法禁用。要导出接口可以，不要和web扯上关系。

2023-04-09 14:25 UTC, fumiama commented
job的接口不要出现任何gin，web有关的内容。它应当是与网络、框架无关的。

2023-04-09 14:29 UTC, guohuiyuan commented
> 不允许给job增加web，这相当于引用了web，导致web无法禁用。要导出接口可以，不要和web扯上关系。

没有啊，route是统一导出路由，你注释掉，不执行，RunGui,路由又不会注册

2023-04-09 14:32 UTC, guohuiyuan commented
> 不允许给job增加web，这相当于引用了web，导致web无法禁用。要导出接口可以，不要和web扯上关系。

如果直接导出job的方法，要导出很多方法，一个导出比较方便

2023-04-09 14:33 UTC, fumiama commented
无论如何，不要在job出现gin，一是耦合性太强，二是无谓的体积增大。

2023-04-09 14:44 UTC, guohuiyuan commented
> 无论如何，不要在job出现gin，一是耦合性太强，二是无谓的体积增大。

gin包真的很大吗，大的是前端静态文件

2023-04-09 14:51 UTC, guohuiyuan commented
不加gin也行吧

2023-04-12 06:12 UTC, fumiama requested changes

2023-04-12 06:12 UTC, fumiama commented on job/web.go
> +func Add(j Job) (err error) {
j *Job

2023-04-12 06:12 UTC, fumiama commented on job/web.go
> +type ListRsp struct {
这只有一个成员的封装，我的建议是去掉。

2023-04-12 06:12 UTC, fumiama commented on job/web.go
> +	case 1:
使用const显式定义，如
```go
type JobType uint8
const(
    FullMatchJob JobType = iota+1
)
```

2023-04-12 06:12 UTC, fumiama commented on job/web.go
> +	JobType       int    `json:"jobType"`       // 任务类型,1-指令别名,2-定时任务,3-你问我答
这里就可以写为 JobType JobType

2023-04-12 06:12 UTC, fumiama commented on job/web.go
> +	QuestionType  int    `json:"questionType"`  // 问题类型, jobType=3使用的参数, 1=单独问, 2=所有人问
其它type也如法炮制

2023-04-12 06:12 UTC, fumiama commented on job/web.go
> +func Delete(req DeleteReq) (err error) {
req *DeleteReq

2023-04-23 06:34 UTC, guohuiyuan commented
能合就合了吧

2023-04-24 03:41 UTC, fumiama approved these changes

2023-04-24 03:41 UTC, merged